### ISSUE TITLE
Namespace for Android

### ISSUE THREAD

**Issue by PaulineMoovency** [datadirr/encrypt_decrypt_plus#1]
#The namespace for Android is missing
https://github.com/datadirr/encrypt_decrypt_plus/pull/2

* What went wrong:
A problem occurred configuring project ':encrypt_decrypt_plus'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

**Comment by datadirr** [comment]
Hi,

namespace for android done with encrypt_decrypt_plus: 1.2.0
